
spring:
  application:
    name: car_rent
  datasource:
    url: jdbc:mysql://localhost:3306/arrendadora
    username: root
    password: diogenes
  jpa:
    hibernate:
      ddl-auto: update # Crea/actualiza el esquema de la base de datos
    show-sql: true     # Imprime las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Dialecto específico para MySQL
    defer-datasource-initialization: true # Evita problemas de inicialización

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    enabled: true
    cache: false

server:
  port: 8080

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

twilio:
  account:
    sid: AC27a700d98e81cf2ab213ec3f4a3c14a6
  auth:
    token: 317d3dec6ed226d15aacbc62dc97b5e8
  phone:
    number: +12766885567
jwt:
  secret: tDRRl8rqyhx05TfgfrQXBgI4qsJkGiuPGo6FwhSSKHO5eeR/emr5pOTV2GqpQG6RLCB/Ey4eAzUEcBQ33VY5Ng==
  header: Authorization
  prefix: Bearer
  expiration-time: 86400000