spring:
  application:
    name: car_rent
  datasource:
    url: jdbc:mysql://localhost:3306/arrendadora
    username: root
    password: diogenes
  jpa:
    hibernate:
      ddl-auto: update # Crea/actualiza el esquema de la base de datos
    show-sql: true     # Imprime las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Dialecto específico para MySQL 8 (o superior)
    defer-datasource-initialization: true # Importante para evitar problemas de concurrencia
server:
  port: 8080