spring:
  application:
    name: car_rent

  flyway:
    enabled: true
    locations: classpath:db/migrations
    baseline-on-migrate: false
    validate-on-migrate: true
    out-of-order: false
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update # Crea/actualiza el esquema de la base de datos
    show-sql: true     # Imprime las consultas SQL en la consola
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect # Dialecto específico para MySQL
  mvc:
    static-path-pattern: /static/**

application:
  initial-admin:
    username: ${INIT_ADMIN_USER}
    email: ${INIT_ADMIN_EMAIL}
    password: ${INIT_ADMIN_PASS}

twilio:
  account-sid: ${TWILIO_SID}
  auth-token: ${TWILIO_TOKEN}
  phone-number: ${TWILIO_PHONE}
  enabled: true
jwt:
  secret: ${JWT_SECRET}
  header: Authorization
  prefix: Bearer
  expiration-time: 86400000
vonage:
  api-key: ${VONAGE_API_KEY}
  api-secret: ${VONAGE_API_SECRET}
  from-number: ${VONAGE_PHONE}

sms:
  provider: vonage

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.messaging: DEBUG
    org.springframework.web.socket: DEBUG
    org.flywaydb: DEBUG

springdoc:
  swagger-ui:
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: alpha